#!/usr/bin/env bash
# Stops the 7-highlander process by sending it SIGTERM

# Find the PID(s) of the 7-highlander process
pids=$(pgrep -f 7-highlander)

# Send SIGTERM to each PID found
for pid in $pids; do
    kill -SIGTERM "$pid"
done
