#!/usr/bin/env bash
# Infinite loop that prints "To infinity and beyond" and handles SIGTERM

# Trap SIGTERM signal
trap 'echo "I am invincible!!!"' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
