#!/usr/bin/env bash
# Displays "Best School" 10 times and "Hi" after the 9th iteration using while and if
i=1; while [ $i -le 10 ]; do if [ $i -eq 9 ]; then echo "Best School"; echo "Hi"; else echo "Best School"; fi; ((i++)); done
